from tkinter import *
from tkinter import ttk
from graphs import define_lst
from excel_logic import to_variant

root = Tk()
root.configure(bg='white')
root.title("Домашнее задание")

label = ttk.Label(root, text='Вариант №', background='white', font=('Arial', 12, 'bold'))
label.grid(row=0, column=0, columnspan=3, pady=15, padx=20)

entry = ttk.Entry(root, font=('Arial', 12), width=5)
entry.grid(row=0, column=3, pady=15, padx=10)


def get_entry_value():
    value = entry.get()
    define_lst(int(value))
    root.destroy()

def new_values():
    button1.configure(state=DISABLED)
    button2.configure(state=DISABLED)
    entry.configure(state=DISABLED)

    label1 = ttk.Label(root, text='Rzi, мкм', background='white', width=10)
    label1.grid(row=2, column=0, pady=15)
    entry1 = ttk.Entry(root, width=5)
    entry1.grid(row=2, column=1, pady=15, sticky='w')
    label2 = ttk.Label(root, text='Rzb, мкм', background='white', width=10)
    label2.grid(row=3, column=0, pady=15)
    entry2 = ttk.Entry(root, width=5)
    entry2.grid(row=3, column=1, pady=15, sticky='w')
    label3 = ttk.Label(root, text='λ, град', background='white', width=10)
    label3.grid(row=4, column=0, pady=15)
    entry3 = ttk.Entry(root, width=5)
    entry3.grid(row=4, column=1, pady=15, sticky='w')
    label4 = ttk.Label(root, text='ϕ, град', background='white', width=10)
    label4.grid(row=5, column=0, pady=15)
    entry4 = ttk.Entry(root, width=5)
    entry4.grid(row=5, column=1, pady=15, sticky='w')
    label5 = ttk.Label(root, text='ϕ1, град', background='white', width=10)
    label5.grid(row=6, column=0, pady=15)
    entry5 = ttk.Entry(root, width=5)
    entry5.grid(row=6, column=1, pady=15, sticky='w')

    label6 = ttk.Label(root, text='γ, град', background='white', width=10)
    label6.grid(row=2, column=3, pady=15)
    entry6 = ttk.Entry(root, width=5)
    entry6.grid(row=2, column=4, pady=15, sticky='w')
    label7 = ttk.Label(root, text='r, мм', background='white', width=10)
    label7.grid(row=3, column=3, pady=15)
    entry7 = ttk.Entry(root, width=5)
    entry7.grid(row=3, column=4, pady=15, sticky='w')
    label8 = ttk.Label(root, text='ρ, мм', background='white', width=10)
    label8.grid(row=4, column=3, pady=15)
    entry8 = ttk.Entry(root, width=5)
    entry8.grid(row=4, column=4, pady=15, sticky='w')
    label9 = ttk.Label(root, text='hz, мм', background='white', width=10)
    label9.grid(row=5, column=3, pady=15)
    entry9 = ttk.Entry(root, width=5)
    entry9.grid(row=5, column=4, pady=15, sticky='w')
    label10 = ttk.Label(root, text='v, м/мин', background='white', width=10)
    label10.grid(row=6, column=3, pady=15)
    entry10 = ttk.Entry(root, width=5)
    entry10.grid(row=6, column=4, pady=15, sticky='w')

    label11 = ttk.Label(root, text='t, мм', background='white', width=10)
    label11.grid(row=2, column=7, pady=15)
    entry11 = ttk.Entry(root, width=5)
    entry11.grid(row=2, column=8, pady=15, sticky='w')
    label12 = ttk.Label(root, text='s, мм/об', background='white', width=10)
    label12.grid(row=3, column=7, pady=15)
    entry12 = ttk.Entry(root, width=5)
    entry12.grid(row=3, column=8, pady=15, sticky='w')
    label13 = ttk.Label(root, text='σ.b, МПа', background='white', width=10)
    label13.grid(row=4, column=7, pady=15)
    entry13 = ttk.Entry(root, width=5)
    entry13.grid(row=4, column=8, pady=15, sticky='w')
    label14 = ttk.Label(root, text='σ.02, МПа', background='white', width=10)
    label14.grid(row=5, column=7, pady=15)
    entry14 = ttk.Entry(root, width=5)
    entry14.grid(row=5, column=8, pady=15, sticky='w')

    def add_values():
            lst = []
            lst.append(int(entry1.get()))
            lst.append(float(entry2.get()))
            lst.append(float(entry3.get()))
            lst.append(float(entry4.get()))
            lst.append(float(entry5.get()))
            lst.append(float(entry6.get()))
            lst.append(float(entry7.get()))
            lst.append(float(entry8.get()))
            lst.append(float(entry9.get()))
            lst.append(float(entry10.get()))
            lst.append(float(entry11.get()))
            lst.append(float(entry12.get()))
            lst.append(float(entry13.get()))
            lst.append(float(entry14.get()))

            to_variant(lst)
            button1.configure(state=NORMAL)
            entry.configure(state=NORMAL)
            button2.configure(state=NORMAL)

            label1.destroy()
            label2.destroy()
            label3.destroy()
            label4.destroy()
            label5.destroy()
            label6.destroy()
            label7.destroy()
            label8.destroy()
            label9.destroy()
            label10.destroy()
            label11.destroy()
            label12.destroy()
            label13.destroy()
            label14.destroy()
            entry1.destroy()
            entry2.destroy()
            entry3.destroy()
            entry4.destroy()
            entry5.destroy()
            entry6.destroy()
            entry7.destroy()
            entry8.destroy()
            entry9.destroy()
            entry10.destroy()
            entry11.destroy()
            entry12.destroy()
            entry13.destroy()
            entry14.destroy()
            button3.destroy()


    button3 = ttk.Button(root, text="Внести", command=add_values, width=15)
    button3.grid(row=6, column=7, columnspan=2, pady=15, padx=2)

button1 = ttk.Button(root, text="Рассчитать", command=get_entry_value)
button1.grid(row=0, column=4, columnspan=3, pady=15, padx=10, sticky='w')

button2 = ttk.Button(root, text="Внести новые данные", command=new_values)
button2.grid(row=1, column=0, columnspan=4, sticky='w', pady=15, padx=10)

root.mainloop()
