from tkinter import *
from tkinter import ttk
from graphs import define_lst
from excel_logic import to_variant

root = Tk()
root.configure(bg='white')
root.title("Домашнее задание")

label = ttk.Label(root, text='Вариант №', background='white', font=('Arial', 12, 'bold'))
label.grid(row=0, column=0, columnspan=2, pady=5, padx=5)

entry = ttk.Entry(root, font=('Arial', 12), width=5)
entry.grid(row=0, column=3, pady=5, padx=20)


def get_entry_value():
    value = entry.get()
    define_lst(int(value))
    root.destroy()

def new_values():
    button1.configure(state=DISABLED)
    button2.configure(state=DISABLED)
    entry.configure(state=DISABLED)

    label1 = ttk.Label(root, text='Rzi', background='white')
    label1.grid(row=2, column=0, pady=10, padx=5)
    entry1 = ttk.Entry(root, width=5)
    entry1.grid(row=2, column=1, pady=10, padx=5)
    label2 = ttk.Label(root, text='Rzb', background='white')
    label2.grid(row=3, column=0, pady=10, padx=5)
    entry2 = ttk.Entry(root, width=5)
    entry2.grid(row=3, column=1, pady=10, padx=5)
    label3 = ttk.Label(root, text='λ', background='white')
    label3.grid(row=4, column=0, pady=10, padx=5)
    entry3 = ttk.Entry(root, width=5)
    entry3.grid(row=4, column=1, pady=10, padx=5)
    label4 = ttk.Label(root, text='ϕ', background='white')
    label4.grid(row=5, column=0, pady=10, padx=5)
    entry4 = ttk.Entry(root, width=5)
    entry4.grid(row=5, column=1, pady=10, padx=5)
    label5 = ttk.Label(root, text='ϕ1', background='white')
    label5.grid(row=6, column=0, pady=10, padx=5)
    entry5 = ttk.Entry(root, width=5)
    entry5.grid(row=6, column=1, pady=10, padx=5)

    label6 = ttk.Label(root, text='γ', background='white')
    label6.grid(row=2, column=2, pady=10, padx=5)
    entry6 = ttk.Entry(root, width=5)
    entry6.grid(row=2, column=3, pady=10, padx=5)
    label7 = ttk.Label(root, text='r', background='white')
    label7.grid(row=3, column=2, pady=10, padx=5)
    entry7 = ttk.Entry(root, width=5)
    entry7.grid(row=3, column=3, pady=10, padx=5)
    label8 = ttk.Label(root, text='ρ', background='white')
    label8.grid(row=4, column=2, pady=10, padx=5)
    entry8 = ttk.Entry(root, width=5)
    entry8.grid(row=4, column=3, pady=10, padx=5)
    label9 = ttk.Label(root, text='hz', background='white')
    label9.grid(row=5, column=2, pady=10, padx=5)
    entry9 = ttk.Entry(root, width=5)
    entry9.grid(row=5, column=3, pady=10, padx=5)
    label10 = ttk.Label(root, text='v', background='white')
    label10.grid(row=6, column=2, pady=10, padx=5)
    entry10 = ttk.Entry(root, width=5)
    entry10.grid(row=6, column=3, pady=10, padx=5)

    label11 = ttk.Label(root, text='t', background='white')
    label11.grid(row=2, column=4, pady=10, padx=5)
    entry11 = ttk.Entry(root, width=5)
    entry11.grid(row=2, column=5, pady=10, padx=5)
    label12 = ttk.Label(root, text='s', background='white')
    label12.grid(row=3, column=4, pady=10, padx=5)
    entry12 = ttk.Entry(root, width=5)
    entry12.grid(row=3, column=5, pady=10, padx=5)
    label13 = ttk.Label(root, text='σ.b', background='white')
    label13.grid(row=4, column=4, pady=10, padx=5)
    entry13 = ttk.Entry(root, width=5)
    entry13.grid(row=4, column=5, pady=10, padx=5)
    label14 = ttk.Label(root, text='σ.02', background='white')
    label14.grid(row=5, column=4, pady=10, padx=5)
    entry14 = ttk.Entry(root, width=5)
    entry14.grid(row=5, column=5, pady=10, padx=5)

    def add_values():
            lst = []
            lst.append(int(entry1.get()))
            lst.append(float(entry2.get()))
            lst.append(float(entry3.get()))
            lst.append(float(entry4.get()))
            lst.append(float(entry5.get()))
            lst.append(float(entry6.get()))
            lst.append(float(entry7.get()))
            lst.append(float(entry8.get()))
            lst.append(float(entry9.get()))
            lst.append(float(entry10.get()))
            lst.append(float(entry11.get()))
            lst.append(float(entry12.get()))
            lst.append(float(entry13.get()))
            lst.append(float(entry14.get()))

            to_variant(lst)
            button1.configure(state=NORMAL)
            entry.configure(state=NORMAL)
            button2.configure(state=NORMAL)

            label1.destroy()
            label2.destroy()
            label3.destroy()
            label4.destroy()
            label5.destroy()
            label6.destroy()
            label7.destroy()
            label8.destroy()
            label9.destroy()
            label10.destroy()
            label11.destroy()
            label12.destroy()
            label13.destroy()
            label14.destroy()
            entry1.destroy()
            entry2.destroy()
            entry3.destroy()
            entry4.destroy()
            entry5.destroy()
            entry6.destroy()
            entry7.destroy()
            entry8.destroy()
            entry9.destroy()
            entry10.destroy()
            entry11.destroy()
            entry12.destroy()
            entry13.destroy()
            entry14.destroy()
            button3.destroy()


    button3 = ttk.Button(root, text="Внести", width=20, command=add_values)
    button3.grid(row=6, column=5, columnspan=2, pady=25, padx=5, sticky='w')

button1 = ttk.Button(root, text="Рассчитать", width=10, command=get_entry_value)
button1.grid(row=0, column=4, pady=25, padx=20)

button2 = ttk.Button(root, text="Внести новые данные", width=20, command=new_values)
button2.grid(row=1, column=0, columnspan=2, pady=25, padx=20, sticky='w')

root.mainloop()
